add_test(NAME dbc-generation COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/protocol/generate_can.py --product-root ${METER_PRODUCT_ROOT} --check)
add_executable(test-demo-pdo "${METER_PRODUCT_ROOT}/tests/test_pdo.c")
target_link_libraries(test-demo-pdo PRIVATE meter_product_data meter_core meter_runtime)
add_test(NAME demo-pdo COMMAND test-demo-pdo)
add_test(NAME demo-pdo-dbc COMMAND ${Python3_EXECUTABLE} "${METER_PRODUCT_ROOT}/tests/test_pdo_dbc.py" $<TARGET_FILE:test-demo-pdo>)
add_executable(test-demo-settings "${METER_PRODUCT_ROOT}/tests/test_settings_app.c")
target_link_libraries(test-demo-settings PRIVATE meter_product_data meter_core)
add_test(NAME demo-settings-app COMMAND test-demo-settings)
add_executable(test-presentation "${METER_PRODUCT_ROOT}/tests/test_presentation.c")
target_link_libraries(test-presentation PRIVATE meter_product_data meter_core)
add_test(NAME product-presentation COMMAND test-presentation)
add_library(meter_synthetic STATIC "${METER_PRODUCT_ROOT}/sim/synthetic.c")
target_link_libraries(meter_synthetic PUBLIC meter_runtime)
target_include_directories(meter_synthetic PUBLIC "${METER_PRODUCT_ROOT}")
add_executable(test-platform "${METER_PRODUCT_ROOT}/tests/test_platform.c")
target_link_libraries(test-platform PRIVATE meter_core meter_runtime meter_protocol_product meter_catalog meter_ui_math meter_synthetic)
foreach(suite contracts core runtime protocol widgets settings)
    add_test(NAME ${suite} COMMAND test-platform ${suite})
endforeach()
add_test(NAME can-replay COMMAND ${Python3_EXECUTABLE} "${METER_PRODUCT_ROOT}/tests/test_replay.py" $<TARGET_FILE:meter-protocol-runner>)
add_test(NAME catalog COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/generate_catalog.py --product-root ${METER_PRODUCT_ROOT} --check)
add_test(NAME fonts COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/generate_fonts.py --product-root ${METER_PRODUCT_ROOT} --check)
add_test(NAME assets COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_assets.py --product-root ${METER_PRODUCT_ROOT})
add_test(NAME demo-docs-sync COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/check_docs_sync.py --root ${METER_PRODUCT_ROOT})
add_test(NAME demo-docs-evidence COMMAND ${Python3_EXECUTABLE} ${METER_PRODUCT_ROOT}/tools/check_docs.py)
add_test(NAME demo-source-digest COMMAND ${Python3_EXECUTABLE} ${METER_PRODUCT_ROOT}/tools/test_capture_sources.py)
if(METER_BUILD_UI)
    add_executable(test-pagination "${METER_PRODUCT_ROOT}/tests/test_pagination.c")
    target_link_libraries(test-pagination PRIVATE meter_ui_product meter_platform meter_core)
    add_test(NAME ui-pagination COMMAND test-pagination)
    add_executable(test-update-ui "${METER_PRODUCT_ROOT}/tests/test_update_ui.c")
    target_link_libraries(test-update-ui PRIVATE meter_ui_product)
    add_test(NAME update-ui COMMAND test-update-ui)
    add_executable(test-i18n-ui "${METER_PRODUCT_ROOT}/tests/test_i18n_ui.c")
    target_link_libraries(test-i18n-ui PRIVATE meter_ui_product meter_platform meter_core)
    add_test(NAME i18n-ui COMMAND test-i18n-ui)
    add_executable(test-clock-ui "${METER_PRODUCT_ROOT}/tests/test_clock_ui.c")
    target_link_libraries(test-clock-ui PRIVATE meter_ui_product meter_product_data meter_platform meter_core)
    add_test(NAME clock-ui COMMAND test-clock-ui)
    add_test(NAME ui-fixtures COMMAND ${Python3_EXECUTABLE} "${METER_PRODUCT_ROOT}/tests/test_fixtures.py" $<TARGET_FILE:meter-protocol-runner> $<TARGET_FILE:meter-demo>)
    add_test(NAME sdl-smoke COMMAND meter-demo --smoke)
    add_test(NAME demo-scenarios COMMAND ${Python3_EXECUTABLE} "${METER_PRODUCT_ROOT}/tests/test_scenarios.py" $<TARGET_FILE:meter-demo>)
endif()
